version: 2.1
orbs:
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.7.0
  node: circleci/node@5.1.0
  docker: circleci/docker@2.1.4
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.7
    working_directory: ~/SCTP-SE-MODULE03-JAVA-PROJECTTEAM02
    steps:
      - checkout
      - run: mvn install -DskipTests

  test:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn test
    
  build-and-push:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run: mvn clean package
      - run: 
          name: Build and push image to DockerHub
          command: | 
            docker build -t joelchua2403/education-workspace . 
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker push joelchua2403/education-workspace
      - run:
          name: Heroku Container Push
          command: | 
            heroku container:login
            heroku container:push web -a harbourbookingsystem
            heroku container:release web -a harbourbookingsystem
            

  snyk-scan:
      docker:
          - image: cimg/openjdk:17.0.7
      environment:
          IMAGE_NAME: joelchua2403/education-workspace
      steps:
        - checkout
        - run: mvn clean package
        - setup_remote_docker
        - docker/check
        - run: docker build -t joelchua2403/education-workspace .
        - snyk/scan: 
            docker-image-name: joelchua2403/education-workspace
            severity-threshold: critical


workflows:
  ci_flow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - test:
          requires:
            - build
      - snyk-scan:
          requires:
            - test
          filters:
            branches: 
              only: develop
  cicd_flow:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
          filters:
            branches: 
              only: release
     