version: 2.1
orbs:
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0
<<<<<<< HEAD

=======
>>>>>>> 6c97d97 (add scan job)
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.7
    working_directory: ~/SCTP-SE-MODULE03-JAVA-PROJECTTEAM02
    steps:
      - checkout
      - run: mvn install -DskipTests

  test:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn test

  scan:
     docker:
            - image: cimg/node:16.10
        environment:
            IMAGE_NAME: edisonzsq/education-space
        steps:
            - checkout
            - setup_remote_docker      
            - docker/check
            - run: docker build -t joelchua2403/education-workspace .
            - snyk/scan: 
                docker-image-name: joelchua2403/education-workspace
    
  build-and-push:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - setup_remote_docker
      - checkout
      - run: mvn clean package
      - run: 
          name: Build and push image to DockerHub
          command: | 
            docker build -t joelchua2403/education-workspace . 
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker push joelchua2403/education-workspace

  deploy:
    docker:
        - image: cimg/openjdk:17.0.7
    steps:
        - setup_remote_docker      
        - heroku/install
        - checkout
        - run:
            name: Heroku Container Push
            command: | 
                heroku container:login
                heroku container:push web -a joelchua2403-su-devops
                heroku container:release web -a joelchua2403-su-devops

  snyk-scan:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: npx snyk test --severity-threshold=medium

workflows:
  ci_flow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - test:
          requires:
            - build
          filters:
            branches:
              only: develop 

  cicd_flow:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - test:
          requires:
            - build
          filters:
            branches:
              only: release 
      - scan:
          requires:
            - test
          filters:
            branches: 
              only: release
      - build-and-push:
          requires:
            - test
            - scan
          filters:
            branches: 
              only: release
      - deploy:
          requires:
            - build-and-push
          filters:
            branches: 
              only: release

  heroku_workflow:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: master

  snyk_workflow:
    jobs:
      - snyk-scan:
          filters:
            branches:
              only: develop
            tags:
              only: /^v.*/  
