version: 2.1
orbs:
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.7
    working_directory: .
    steps:
      - checkout
      - run: mvn install -DskipTests

  test:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - run: mvn test
    
  build-and-push:
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - setup_remote_docker
      - checkout
      - run: mvn clean package
      - run: 
          name: Build and push image to DockerHub
          command: | 
            docker build -t joelchua2403/education-workspace . 
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker push joelchua2403/education-workspace

  deploy:
    docker:
        - image: cimg/openjdk:17.0.7
    steps:
        - setup_remote_docker      
        - heroku/install
        - checkout
        - run:
            name: Heroku Container Push
            command: | 
                heroku container:login
                heroku container:push web -a joelchua2403-su-devops
                heroku container:release web -a joelchua2403-su-devops

workflows:
  ci_flow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - test:
          requires:
            - build
          filters:
            branches:
              only: develop 
  cicd_flow:
    jobs:
      - build:
          filters:
            branches:
              only: release
      - test:
          requires:
            - build
          filters:
            branches:
              only: release 
      - build-and-push:
          requires:
            - test
          filters:
            # tags:
            #   only: /^v.*/  
            branches: 
              only: release
      - deploy:
          requires:
            - build-and-push
          filters:
            # tags:
            #   only: /^v.*/
            branches: 
              only: release
